language: node_js
before_install:
  - sudo apt-get -qq update
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - npm run istanbul
  - npm run eslint
  - greenkeeper-lockfile-upload
node_js:
  - "9"
